### ISSUE TITLE
Comment blocks disable syntax highlighting completely

### ISSUE THREAD

**Issue by klickreflex** [DanielSiepmann/Sublime-Text-TypoScript#2]
If I have a comment block inside any TypoScript file everything below that comment won't be highlighted anymore. Is this a known issue? Running Sublime 3126 on OS 10.12.1.

Regards,
Daniel

**Comment by kitzberger** [comment]
@klickreflex : can you provide an example?

**Comment by klickreflex** [comment]
Yes, but I found the issue already. All my code blocks had a space before the closing `*/` which, I just learned, is not ok by the spec. If I remove that it works. 

But still, as I work with a lot of existing code that is commented like that it would be nice if there was a way to allow highlighting in these files without having to change all of them.

    /*
     * XYZ configuration.
     */

**Comment by kitzberger** [comment]
I just had a look into the TypoScript parsing engine and since TYPO3 ltrims all lines anyway whitespaces in front of the closing sign are actually supported even though the spec says differently. Thanks for the hint ;-)

Release should be available soon.
